//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProperty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMail
    {
        public int Id { get; set; }
        public string sender { get; set; }
        public string sEmail { get; set; }
        public string senderContact { get; set; }
        public string messages { get; set; }
    }
}
