//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProperty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        public int Prop_id { get; set; }
        public string Prop_Desc { get; set; }
        public string Prop_Type { get; set; }
        public string Prop_Stat { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> BathRoom { get; set; }
        public Nullable<int> Garage { get; set; }
        public Nullable<double> Price { get; set; }
        public string Cities { get; set; }
        public string Address { get; set; }
    }
}
